Imports System
Imports System.Security.Permissions
Imports System.Runtime.Serialization

''' <summary>
'''     The exception that is thrown if an MSMQHelper internal error occurs.
''' </summary>
''' <remarks>
'''     Exceptions associated with the MSMQHelperException class are generated by internal errors within MSMQHelper that should be dealt with through your code.
''' </remarks>

<Serializable()> _
Public Class MsmqHelperException
    Inherits Exception

    Private fieldData As String

    Public Sub New()
    End Sub

    ' Add any type-specific logic, and supply the default message.
    Public Sub New(ByVal message As String)
        MyBase.New(message)
    End Sub

    ' Add any type-specific logic.
    Public Sub New(ByVal message As String, ByVal innerException As Exception)
        MyBase.New(message, innerException)
    End Sub

    ' Add any type-specific logic for inner exceptions.
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New(info, context)
        ' Implement type-specific deserialization logic.
        fieldData = info.GetString("fieldData")
    End Sub

    <SecurityPermissionAttribute(SecurityAction.Demand, SerializationFormatter:=True)> _
    Public Overrides Sub GetObjectData(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        ' Implement type-specific serialization logic and call base serializer.
        info.AddValue("fieldData", fieldData)
        MyBase.GetObjectData(info, context)
    End Sub

End Class
